# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5894decd483eb12b61ef0dae3fa4d9a7de812a770d4f71212b7ea49b707a77b9a8dc86bb49a2b740ba86e40d0d5ab4da49a418dcdf560106678f5bb4d2ff3347

test:
  secret_key_base: 497af42bb8438af98dfa738cc201bbcc42b75b6427e7b6f481a56bc2892d9c94a41cd85b3b9b042bbb868a51f245c518d3d81310c71f730400730924a6430e4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
